name: benchmarks
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.2
  - nb_conda_kernels=2.3.1
  - pip:
      - gdown==5.1.0
      - matplotlib==3.7.5
      - numpy==1.24.3
      - pandas==2.0.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - targetnet==0.0.1
      - tensorflow==2.13.1
      - tensorflow-addons==0.21.0
      - torch==2.2.1
      - viennarna==2.6.4
